version: '3.7'

services:
  workers:
    image: gprasad09/spark_withuser:latest
    hostname: sr_worker
    deploy:
      replicas: 6
      resources:
        limits:
          cpus: "4"
      placement:
        constraints:
          - node.role == worker
          - replicas-max-per-node=2
      restart_policy:
        condition: on-failure
      labels:
        - "sr_worker"
    networks:
      - spark-net
networks:
  spark-net:
    driver: overlay
    attachable: true	  
